### ISSUE TITLE
update zod version to latest ^4.

### ISSUE THREAD

**Issue by Nirator78** [openai/openai-agents-js#376]
Would it be possible to update this package to support Zod v4 (^4.0.0)?
Many projects are already moving to the latest version, and having official support here would be very helpful.

**Comment by seratch** [comment]
We currently support only Zod v3, and the underlying `openai` package also depends on v3. In addition, from my understanding, supporting both v3 and v4 at the same time is quite challenging (maybe even impossible).

For these reasons, we don’t have immediate plans to migrate. That said, the SDK should definitely move to v4 in the long run.

**Comment by Nirator78** [comment]
Thank for your answer

**Comment by pvarouktsis** [comment]
Hey @seratch,

Can you include zod@3 in your `package.json` to infer the `ZodObject` type from your own dependencies instead of inferring the type from our own dependency.

The case/issue is that I have already installed zod@4 with access to zod@3 (via `zod/v3` importing) but the type of `ZodObject` is **wrong** as it is inferring the types of our own **default** dependency version, that of zod@4.

Also, the above might be relevant with another issue I encountered that of:
```
Invalid schema for function 'myFunctionTool': schema must be a JSON Schema of 'type: \"object\"', got 'type: \"None\"'.
```
That is, using **our** default zod dependency version for handling.

**Comment by dkundel-openai** [comment]
@pvarouktsis we tried to ship our own Zod 3 with a variety of approaches but different package managers were handling dependency resolution poorly resulting in bigger Zod issues. I think maybe changing at least our import statements back to `'zod/v3'` as opposed to `'zod'` should fix the problem @seratch ?

**Comment by seratch** [comment]
> changing at least our import statements back to 'zod/v3' as opposed to 'zod' should fix the problem

Actually we did this before but it was not a solution. If we go with `zod/v3` import, it never works with `zod` imports even with `zod@3`. `zod` in v3 just refers to `zod/v3` inside `zod` package. However, when using our zod interface from user code, `zod` and` zod/v3` are not the same. Thus, this could not be a solution.

I hear zod resolution may be still confusing, but asking users to use `zod@3` is the only way to avoid any TSC compilation errors with broad range of versions. Also, unfortunately there is no way to support both `zod@3` and `zod@4` at a time for library maintainers relying on `zod`. If you're interested in the context, check https://github.com/openai/openai-agents-js/issues/187 and the linked issues and PRs.

We may be able to take a different approach when migrating to v4, but currently our `openai` package still relies on zod@3, plus migrating to v4 is a big breaking change for existing users. So, it may take some time.

**Comment by pvarouktsis** [comment]
Perfect! Thanks for the clarification and for referencing the zod issues respectively!

I will probably refactor it to `JsonObjectSchemaStrict` for now.

**Comment by Tiscs** [comment]
Since `openai@^6.0.0`, the package has already migrated to **Zod v4** (see [package.json](https://github.com/openai/openai-node/blob/v6.0.0/package.json#L79)). This means downstream projects depending on `openai` can safely upgrade to Zod v4 without compatibility issues. It might be worth updating the related dependencies and documentation here to reflect that the underlying `openai` SDK no longer locks us to Zod v3.

**Comment by Tiscs** [comment]
After analyzing the source code of `openai-agents-js`, I found two remaining blockers that prevent upgrading to `zod@^4`:

1. The `examples/ai-sdk-v1` package depends on `ai-sdk/openai@^1`, which requires `zod@^3`.
2. The `docs` and `examples/docs` packages depend on `typedoc-plugin-zod@^1`, which also requires `zod@^3`.

For issue (1), it might be reasonable to drop support for `ai-sdk/openai@^1` (as of now, the latest version of `ai-sdk/openai` is already `3.0.x`).  
For issue (2), there doesn’t seem to be a good solution available yet.
